import Link from "next/link";
import {routeMetadata} from "@/lib/seo";
import {productNavGroups,serviceNavItems} from "@/lib/navigation";
import {WhatsAppCTA} from "@/components/WhatsAppCTA";

export const metadata=routeMetadata("/soluciones","Productos y soluciones metálicas en Santiago","Explora productos y servicios de RINON: camarotes, camas, camas balinesas, mesas, escritorios, cierres, rejas, portones, mallas, estructuras y fabricación metálica a medida.");

const groupCopy:Record<string,{kicker:string;body:string}>={
 "Camas y descanso":{kicker:"CAMAS Y DESCANSO",body:"Camarotes, camas metálicas y camas balinesas para hogar, instituciones, exterior y compras por volumen."},
 "Mobiliario y equipamiento":{kicker:"MOBILIARIO",body:"Mesas, escritorios, racks, soportes y equipamiento para hogar, empresa e instituciones."},
 "Cierres y accesos":{kicker:"CIERRES Y ACCESOS",body:"Cierres, rejas, mallas y portones definidos según medidas, accesos, terreno y uso."},
 "Estructuras":{kicker:"ESTRUCTURAS",body:"Estructuras y fabricaciones especiales desde plano, foto, croquis, muestra o medidas."},
};

export default function SolutionsPage(){return <main className="v5-editorial-page rinon-product-finder" data-sgeo-owner="soluciones">
 <section className="rinon-finder-hero"><div className="container"><div className="v2-eyebrow">PRODUCTOS · SERVICIOS · PROYECTOS</div><h1>Productos y soluciones metálicas para cada tipo de requerimiento.</h1><p>Parte por el producto, el servicio o el resultado que necesitas. Si tu requerimiento no encaja en una categoría estándar, puedes pasar directamente a fabricación a medida con una foto, plano, croquis, muestra o medidas.</p><div className="v2-actions"><Link className="v2-btn orange" data-event="quote_start" data-cta-location="solutions_hero" href="/cotizar">Cotizar requerimiento</Link><Link className="v2-btn outline" href="/fabricacion-metalica">Proyectos a medida</Link><WhatsAppCTA location="solutions_hero" label="Orientarme por WhatsApp" className="v2-btn outline"/></div></div></section>

 <section className="v2-solution-section"><div className="container"><div className="section-head"><div><div className="v2-eyebrow">PRODUCTOS Y FAMILIAS</div><h2>Elige primero la categoría que más se parece a tu necesidad.</h2></div><p>Cada landing conserva una intención propia para que puedas comparar alcance, antecedentes necesarios y forma de cotizar sin mezclar productos distintos.</p></div><div className="rinon-finder-grid">{productNavGroups.map((group,index)=>{const copy=groupCopy[group.label];return <section className="rinon-finder-family" key={group.label}><header><span>0{index+1} · {copy?.kicker??group.label}</span><h2>{group.label}</h2><p>{copy?.body}</p></header><div>{group.items.map(item=><Link key={item.href} href={item.href}><strong>{item.label}</strong><small>{item.description}</small><b>↗</b></Link>)}</div></section>})}</div></div></section>

 <section className="v2-solution-section soft"><div className="container"><div className="section-head"><div><div className="v2-eyebrow">SERVICIOS DE TALLER Y TERRENO</div><h2>Cuando lo que necesitas es un proceso o una intervención.</h2></div><p>Soldadura, corte, pintura, instalación y reparación tienen rutas propias. La fabricación a medida vive en Proyectos a medida para no duplicar conceptos ni competir por la misma intención de búsqueda.</p></div><div className="v2-resource-grid rinon-service-cards">{serviceNavItems.map(item=><Link className="resource-card" key={item.href} href={item.href}><span>SERVICIO</span><h3>{item.label}</h3><p>{item.description}</p><b>Ver servicio →</b></Link>)}</div></div></section>

 <section className="v2-solution-section"><div className="container"><div className="section-head"><div><div className="v2-eyebrow">NO SABES QUÉ CATEGORÍA ELEGIR</div><h2>Describe el resultado y nosotros partimos desde ahí.</h2></div><p>No necesitas conocer el nombre técnico de la solución. Explica qué debe resolver, dónde se usará y qué antecedente tienes disponible.</p></div><div className="v2-step-grid"><article><span>01</span><h3>Producto conocido</h3><p>Indica modelo o tipo, cantidad y destino.</p></article><article><span>02</span><h3>Trabajo de taller</h3><p>Explica proceso, pieza, material o intervención que necesitas evaluar.</p></article><article><span>03</span><h3>Proyecto a medida</h3><p>Envía foto, plano, croquis, muestra o dimensiones disponibles.</p></article><article><span>04</span><h3>Empresa o volumen</h3><p>Incluye cantidad, destino y fecha objetivo para ordenar la compra.</p></article></div><div className="v2-actions"><Link className="v2-btn outline" href="/empresas">Compra para empresa</Link><Link className="v2-btn outline" href="/fabricacion-metalica">Fabricación a medida</Link></div></div></section>

 <section id="cotizar" className="v2-final-cta"><div className="container"><div><div className="v2-eyebrow">SIGUIENTE PASO</div><h2>¿Ya sabes qué necesitas o prefieres que te orientemos?</h2><p>Envía el requerimiento por formulario o comparte una referencia por WhatsApp. Si falta información, separamos lo confirmado de lo que todavía debe definirse.</p></div><div className="v2-final-actions"><Link className="v2-btn orange" data-event="quote_start" data-cta-location="solutions_footer" href="/cotizar">Cotizar requerimiento</Link><WhatsAppCTA location="solutions_footer" label="Hablar por WhatsApp" className="v2-btn outline"/><Link className="v2-btn outline" href="/fabricacion-metalica">Proyectos a medida</Link></div></div></section>
 </main>}
