import Link from "next/link";
import {routeMetadata} from "@/lib/seo";
import {publicAddressDisplay,publicPhoneDisplay,publicPhoneHref} from "@/lib/contact";
import {whatsappUrl} from "@/lib/whatsapp";
import {MapPanel} from "@/components/MapPanel";

export const metadata=routeMetadata("/contacto","Contacto y cotizaciones","Contacta a RINON para evaluar fabricación metálica, estructuras, cierres, camarotes, mobiliario y proyectos a medida desde San Bernardo.");

export default function Page(){
 const whatsapp=whatsappUrl(); const phone=publicPhoneHref();
 return <main className="v5-editorial-page rinon-contact" data-sgeo-owner="contacto">
  <section className="v2-solution-hero rinon-contact-hero"><div className="container rinon-contact-hero-grid"><div><div className="v2-eyebrow">CONTACTO · SAN BERNARDO</div><h1>Cuéntanos qué necesitas.</h1><p>Si tienes una foto, plano, croquis, cantidad o medidas aproximadas, envíalas. Si todavía estás definiendo la idea, parte por lo que ya sabes.</p><div className="v2-actions"><Link className="v2-btn orange" data-event="quote_start" data-cta-location="contact_hero" href="/cotizar">Cotizar</Link>{whatsapp?<a className="v2-btn outline" data-event="contact_whatsapp" data-cta-location="contact_hero" href={whatsapp} target="_blank" rel="noopener noreferrer">WhatsApp</a>:null}</div><div className="v2-kickers"><span>Particulares</span><span>Empresas</span><span>Unidad o volumen</span><span>{publicAddressDisplay()}</span></div></div><aside className="rinon-contact-choice" aria-label="Formas de contactar a RINON"><span>ELIGE CÓMO EMPEZAR</span><Link data-event="quote_start" data-cta-location="contact_choice_quote" href="/cotizar"><b>01</b><strong>Cotizar</strong><small>Ordena producto, cantidad, medidas y ubicación.</small><em>↗</em></Link>{whatsapp?<a href={whatsapp} target="_blank" rel="noopener noreferrer" data-event="contact_whatsapp" data-cta-location="contact_hero_panel"><b>02</b><strong>WhatsApp</strong><small>Ideal para enviar una referencia o aclarar una duda.</small><em>↗</em></a>:null}<Link data-event="quote_start" data-cta-location="contact_choice_b2b" href="/cotizar?client=b2b"><b>03</b><strong>Empresa / volumen</strong><small>Parte por cantidad, destino y fecha objetivo.</small><em>↗</em></Link><a href="#ubicacion"><b>04</b><strong>Cómo llegar</strong><small>Estamos en Portezuelo 1506, San Bernardo.</small><em>↓</em></a></aside></div></section>

  <section className="v2-solution-section"><div className="container"><div className="rinon-contact-direct"><div><span>WHATSAPP</span><strong>{publicPhoneDisplay()}</strong>{whatsapp?<a href={whatsapp} target="_blank" rel="noopener noreferrer" data-event="contact_whatsapp" data-cta-location="contact_direct">Escribir ahora ↗</a>:null}</div><div><span>TELÉFONO</span><strong>{publicPhoneDisplay()}</strong>{phone?<a href={phone} data-event="contact_phone" data-cta-location="contact_direct">Llamar ↗</a>:null}</div><div><span>TALLER</span><strong>San Bernardo</strong><p>{publicAddressDisplay()}<br/>Región Metropolitana</p></div></div></div></section>

  <div className="container rinon-map-wrap"><MapPanel compact/></div>

  <section className="v2-solution-section soft"><div className="container"><div className="section-head"><div><div className="v2-eyebrow">PARA AVANZAR MÁS RÁPIDO</div><h2>Con cuatro datos podemos empezar.</h2></div><p>No todos aplican a todos los trabajos. Envía lo que tengas y completamos solo lo necesario durante la evaluación.</p></div><div className="card-grid"><article><span>01</span><h3>Qué necesitas</h3><p>Producto, estructura, cierre, reparación o una explicación simple del problema.</p></article><article><span>02</span><h3>Referencia</h3><p>Plano, foto, croquis, muestra o dimensiones aproximadas.</p></article><article><span>03</span><h3>Cantidad</h3><p>Una unidad, un lote o un volumen estimado.</p></article><article><span>04</span><h3>Ubicación</h3><p>Comuna o región para evaluar logística e instalación cuando corresponda.</p></article></div></div></section>
 </main>}
