import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { cookies } from "next/headers";
import { ADMIN_COOKIE,isAdminEnabled,isValidAdminToken } from "@/lib/admin-auth";
import { isRevenueOpsEnabled,listOpportunities,revenueSummary } from "@/lib/revenue";
export const metadata:Metadata={title:"Oportunidades | RINON",robots:{index:false,follow:false}}; export const dynamic="force-dynamic";
const money=(n:number)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(n);
export default async function Page(){
 if(!isAdminEnabled())notFound();
 const auth=isValidAdminToken((await cookies()).get(ADMIN_COOKIE)?.value); if(!auth)return <main className="p-10"><p>No autorizado.</p><Link href="/admin">Volver</Link></main>;
 if(!isRevenueOpsEnabled())return <main className="mx-auto max-w-5xl p-10"><p className="text-sm text-orange-700 font-semibold">REVENUE OPS PREPARADO</p><h1 className="mt-2 text-3xl font-bold">Oportunidades y margen</h1><p className="mt-4 text-gray-600">El código está listo, pero la migración de Supabase y el flag <code>RINON_REVENUE_OPS_ENABLED</code> permanecen apagados hasta revisar el esquema/RLS real.</p><Link className="mt-6 inline-block underline" href="/admin">← Volver al panel</Link></main>;
 let opportunities=[] as Awaited<ReturnType<typeof listOpportunities>>; let error="";try{opportunities=await listOpportunities()}catch{error="No fue posible cargar oportunidades."}const s=revenueSummary(opportunities);
 return <main className="mx-auto max-w-7xl px-4 py-10"><div className="flex justify-between"><div><p className="text-sm font-semibold text-orange-700">REVENUE OPS</p><h1 className="text-3xl font-bold">Oportunidades</h1></div><Link href="/admin" className="underline">Panel general</Link></div>{error&&<p className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<section className="mt-8 grid gap-4 md:grid-cols-4"><div className="rounded-xl border p-5"><span className="text-sm text-gray-500">Abiertas</span><b className="mt-2 block text-3xl">{s.openCount}</b></div><div className="rounded-xl border p-5"><span className="text-sm text-gray-500">Pipeline neto</span><b className="mt-2 block text-2xl">{money(s.pipeline)}</b></div><div className="rounded-xl border p-5"><span className="text-sm text-gray-500">Pipeline ponderado</span><b className="mt-2 block text-2xl">{money(s.weighted)}</b></div><div className="rounded-xl border p-5"><span className="text-sm text-gray-500">Margen ganado</span><b className="mt-2 block text-2xl">{money(s.wonMargin)}</b></div></section><div className="mt-8 overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-gray-50"><tr><th className="p-3">Actualizada</th><th className="p-3">Empresa</th><th className="p-3">Categoría</th><th className="p-3">Etapa</th><th className="p-3">Venta estimada</th><th className="p-3">Margen estimado</th><th className="p-3">Próxima acción</th></tr></thead><tbody>{opportunities.map(o=><tr key={o.id} className="border-t"><td className="p-3">{new Intl.DateTimeFormat("es-CL",{dateStyle:"short"}).format(new Date(o.updated_at))}</td><td className="p-3"><Link href={`/admin/oportunidades/${o.id}`} className="font-semibold underline">{o.company_name||"Sin empresa"}</Link></td><td className="p-3">{o.category}</td><td className="p-3">{o.stage.replaceAll("_"," ")}</td><td className="p-3">{money(o.estimated_net_sale||0)}</td><td className="p-3">{money(o.estimated_gross_margin||0)}</td><td className="p-3">{o.next_action_at?new Intl.DateTimeFormat("es-CL",{dateStyle:"short"}).format(new Date(o.next_action_at)):"—"}</td></tr>)}</tbody></table></div></main>;
}
