import Image from "next/image";
import Link from "next/link";
import {routeMetadata} from "@/lib/seo";
import {publicAddressDisplay} from "@/lib/contact";
import {WhatsAppCTA} from "@/components/WhatsAppCTA";
import {VisualEvidence} from "@/components/VisualEvidence";

export const metadata=routeMetadata("/","Fabricación metálica a medida en Santiago","Camarotes, camas, mobiliario, cierres, estructuras y servicios de fabricación metálica a medida con RINON en San Bernardo.");

const process=[["01","Cuéntanos","Qué necesitas, para qué se usará y qué antecedentes ya tienes."],["02","Definimos","Revisamos medidas, cantidad y lo que falta confirmar."],["03","Fabricamos","Acordamos la solución fabricable antes de pasar a producción."],["04","Entregamos","Coordinamos despacho o instalación cuando corresponda."]] as const;
const moreSolutions=[["Camas balinesas","/camas-balinesas"],["Mesas","/mesas-metalicas"],["Escritorios","/escritorios-metalicos"],["Equipamiento","/equipamiento-metalico"],["Rejas","/rejas-metalicas"],["Portones","/portones-metalicos"]] as const;

export default function Home(){return <main className="s7-home">
 <section className="s7-hero s7-hero-contained"><div className="container s7-hero-inner"><div className="s7-hero-copy"><span className="s7-kicker">FABRICACIÓN METÁLICA · SAN BERNARDO</span><h1>Lo necesitas<br/>en metal.<br/><em>Lo fabricamos.</em></h1><p>Productos, proyectos y soluciones a medida para empresas y particulares.</p><div className="s7-actions"><Link className="s7-cta" data-event="quote_start" data-cta-location="hero" href="/cotizar">Cotizar <span>↗</span></Link><Link className="s7-text-link" href="#empezar">Ver productos <span>↓</span></Link></div></div><div className="s7-hero-media"><div className="s7-hero-image" data-source-width="720" data-source-height="730"><Image src="/visuals/home-hero-conceptual-welding.webp" alt="Visual conceptual de trabajo metalmecánico" fill sizes="360px" priority unoptimized/></div><span className="s7-concept-note">Visual conceptual · 720 × 730 fuente</span><div className="s7-hero-note" aria-label="Información operativa"><span>Fabricación directa</span><span>Plano · foto · referencia</span><span>{publicAddressDisplay()}</span></div></div></div></section>

 <section className="rinon-entry" id="empezar"><div className="container"><div className="rinon-entry-head"><div><span className="s7-kicker ink">EMPIEZA POR LO QUE NECESITAS</span><h2>Elige cómo empezar.</h2></div><p>No necesitas conocer el nombre técnico exacto. Parte por un producto, un proyecto a medida o una compra para empresa.</p></div><div className="rinon-entry-grid"><Link href="/soluciones"><span>01 · PRODUCTO</span><h3>Necesito un producto.</h3><p>Camarotes, camas, balinesas, mesas, escritorios, cierres, rejas, portones y equipamiento.</p><b>Ver productos →</b></Link><Link href="/fabricacion-metalica"><span>02 · PROYECTO A MEDIDA</span><h3>Necesito fabricar algo especial.</h3><p>Parte con una foto, plano, croquis, muestra, medidas o una explicación de lo que necesitas resolver.</p><b>Ver proyectos a medida →</b></Link><Link href="/empresas"><span>03 · EMPRESA</span><h3>Necesito volumen o un requerimiento B2B.</h3><p>Cantidad, destino, fecha objetivo y especificación para ordenar la compra desde el inicio.</p><b>Soluciones para empresas →</b></Link></div></div></section>

 <section className="s7-solutions" id="soluciones"><div className="container s7-solutions-head" data-reveal><span className="s7-kicker ink">QUÉ FABRICAMOS</span><h2>Tres mundos.<br/>Una misma fabricación.</h2></div>
  <article className="s7-chapter s7-chapter-dark" data-reveal><div className="container s7-chapter-grid"><div className="s7-chapter-media s7-rhino-cut"><VisualEvidence slug="/camarotes" fallback={["producto completo","detalle constructivo","cantidad"]} mode="theatre"/></div><div className="s7-chapter-copy"><span className="s7-index">01</span><small>PRODUCTO / VOLUMEN</small><h3>Camas y<br/>camarotes.</h3><p>Configuraciones metálicas para hogar, instituciones, faenas, alojamientos y proyectos por cantidad.</p><Link href="/camarotes">Explorar camarotes <span>↗</span></Link></div></div></article>
  <article className="s7-chapter s7-chapter-light" data-reveal><div className="container s7-chapter-grid reverse"><div className="s7-chapter-media s7-rhino-cut mirror"><VisualEvidence slug="/cierres-perimetrales" fallback={["sistema completo","postes y paños","contexto"]} mode="theatre"/></div><div className="s7-chapter-copy"><span className="s7-index">02</span><small>PERÍMETRO / ACCESO</small><h3>Cierres y<br/>protecciones.</h3><p>Rejas, portones, mallas y sistemas perimetrales definidos según medidas, accesos y contexto de uso.</p><Link href="/cierres-perimetrales">Explorar cierres <span>↗</span></Link></div></div></article>
  <article className="s7-chapter s7-chapter-graphite" data-reveal><div className="container s7-chapter-grid"><div className="s7-chapter-media s7-rhino-cut"><VisualEvidence slug="/estructuras-metalicas" fallback={["estructura completa","detalle de unión","contexto de uso"]} mode="theatre"/></div><div className="s7-chapter-copy"><span className="s7-index">03</span><small>PROYECTO / A MEDIDA</small><h3>Estructuras<br/>metálicas.</h3><p>Cobertizos, pérgolas, escaleras, plataformas, soportes y estructuras definidas para cada espacio o necesidad.</p><Link href="/estructuras-metalicas">Explorar estructuras <span>↗</span></Link></div></div></article>
  <nav className="container s7-more" aria-label="Más soluciones"><span>Más productos</span>{moreSolutions.map(([label,href])=><Link key={href} href={href}>{label} <b>↗</b></Link>)}</nav>
 </section>

 <section className="s7-process" data-reveal><div className="container"><div className="s7-process-heading"><span className="s7-kicker">CÓMO TRABAJAMOS</span><h2>Un proceso simple.</h2></div><ol className="s7-process-list">{process.map(([n,title,body])=><li key={n}><span>{n}</span><strong>{title}</strong><p>{body}</p></li>)}</ol></div></section>
 <section className="s7-custom" data-reveal><div className="s7-custom-mark" aria-hidden="true"><Image src="/brand/isotipo-rinoceronte-transparent.webp" alt="" fill sizes="45vw" unoptimized/></div><div className="container s7-custom-inner"><span className="s7-kicker">PROYECTOS A MEDIDA</span><h2>Cuando no existe<br/>en un catálogo.</h2><p>Una foto, un plano, un croquis, una muestra o unas medidas pueden ser suficientes para empezar a conversar.</p><Link className="s7-text-link light" href="/fabricacion-metalica">Ver proyectos a medida <span>↗</span></Link></div></section>
 <section className="s7-enterprise" data-reveal><div className="container s7-enterprise-inner"><div><span className="s7-kicker ink">EMPRESAS / VOLUMEN</span><h2>Primero entendemos<br/>qué necesitas fabricar.</h2></div><div className="s7-enterprise-copy"><p>Cantidad, uso, ubicación, antecedentes y plazo objetivo: lo necesario para evaluar compras por volumen y proyectos especiales.</p><Link href="/empresas">Soluciones para empresas <span>↗</span></Link></div></div></section>
 <section className="s7-final" data-reveal><div className="container s7-final-inner"><div><span className="s7-kicker">TU PROYECTO</span><h2>¿Qué necesitas fabricar?</h2></div><div className="s7-final-actions"><Link className="s7-cta" data-event="quote_start" data-cta-location="home_footer" href="/cotizar">Cotizar <span>↗</span></Link><WhatsAppCTA location="home_footer" label="WhatsApp" className="s7-text-link dark"/></div></div></section>
 </main>}
