type Scope = { title:string; good:string[]; define:string[] };
const scopeBySlug:Record<string,Scope>={
  "/camarotes":{title:"Una buena cotización separa modelo de condiciones de compra.",good:["Tienes una referencia o uso objetivo","Puedes indicar cantidad aproximada","Conoces destino o ubicación"],define:["Medidas/configuración vigentes","Modalidad y costo de entrega","Instalación o armado cuando aplique"]},
  "/cierres-perimetrales":{title:"El perímetro se cotiza mejor cuando el terreno entra en la conversación.",good:["Tienes metros y altura aproximados","Puedes mostrar accesos y encuentros","Tienes fotos generales del lugar"],define:["Tipo de anclaje/apoyo","Alcance de instalación","Solución final de cada acceso"]},
  "/estructuras-metalicas":{title:"Fabricación estructural no equivale automáticamente a ingeniería estructural.",good:["Existe función, croquis, plano o medidas","La ubicación y restricciones son conocidas","Puedes explicar el uso del conjunto"],define:["Cálculo o memoria cuando se requiera","Cargas o capacidades que requieran respaldo técnico","Responsabilidad profesional o documentación técnica especial"]},
  "/fabricacion-metalica":{title:"Mientras más claro el uso, menos depende la cotización de supuestos.",good:["Tienes plano, muestra, foto o medidas","Puedes explicar qué debe hacer la pieza","Conoces cantidad o repetición esperada"],define:["Tolerancias críticas","Material/grado cuando sea requisito","Ensayos o documentación técnica específica"]},
  "/equipamiento-metalico":{title:"Un rack o gabinete se diseña alrededor de la operación, no del nombre.",good:["Sabes qué se almacena o equipa","Conoces el espacio disponible","Puedes estimar cantidad"],define:["Cargas o capacidades que requieran respaldo técnico","Anclajes/montaje","Accesorios y terminación final"]},
  "/fabricaciones-especiales":{title:"Una referencia incompleta sirve para evaluar; una especificación crítica debe quedar explícita.",good:["Hay muestra, foto, croquis o función","Se pueden tomar/entregar medidas","Existe una cantidad estimada"],define:["Tolerancias y material crítico","Ingeniería o cálculo requerido","Ensayos o validaciones técnicas especiales"]},
  "/camarote-con-escritorio":{title:"El modelo debe caber y también dejar trabajar y circular.",good:["Tienes medidas del dormitorio","Sabes cuántas unidades necesitas","Puedes compartir una foto del espacio"],define:["Dimensiones y accesorios vigentes","Relación con puertas/ventanas","Entrega/armado aplicable"]},
  "/rejas-metalicas":{title:"La reja se fabrica contra un vano o tramo real.",good:["Tienes ancho/alto aproximados","Puedes mostrar apoyos con fotos","Sabes qué acceso debe mantenerse"],define:["Anclajes definitivos","Alcance de instalación","Terminación específica"]},
  "/portones-metalicos":{title:"El vano no basta: el portón necesita espacio para moverse.",good:["Tienes ancho/alto del acceso","Puedes mostrar el recorrido disponible","Sabes si el uso es peatonal o vehicular"],define:["Sistema de apertura final","Automatización si se requiere","Montaje/anclajes y terminación"]},
};

export function ScopeFitBand({slug}:{slug:string}){
 const scope=scopeBySlug[slug]; if(!scope)return null;
 return <section className="v2-scope-fit"><div className="container"><div className="v2-scope-fit-head"><span className="v2-eyebrow">ALCANCE SIN LETRA CHICA</span><h2>{scope.title}</h2></div><div className="v2-scope-fit-grid"><article><small>BUEN PUNTO DE PARTIDA</small>{scope.good.map(x=><div key={x}><span>✓</span><b>{x}</b></div>)}</article><article className="define"><small>SE CONFIRMA ANTES DE COMPROMETER</small>{scope.define.map(x=><div key={x}><span>→</span><b>{x}</b></div>)}</article></div></div></section>;
}
