const bands: Record<string, { eyebrow:string; title:string; intro:string; items:Array<[string,string,string]> }> = {
  "/camarotes": { eyebrow:"ANTES DE DEFINIR MODELO", title:"Cantidad, configuración y destino cambian la compra.", intro:"La misma referencia puede requerir decisiones distintas según quién la usará, cuántas unidades se necesitan y cómo se entregará.", items:[["01","Configuración","Cama, camarote o variante evaluada para el espacio."],["02","Cantidad","Unidad, lote o compra institucional."],["03","Destino","Ubicación y modalidad de entrega a considerar."]] },
  "/cierres-perimetrales": { eyebrow:"LEVANTAR EL PERÍMETRO", title:"Mide lo que realmente condiciona el cierre.", intro:"Una longitud aproximada ayuda, pero altura, accesos y terreno explican el proyecto completo.", items:[["01","Longitud + altura","Metros lineales y altura de referencia."],["02","Accesos","Portones, puertas y puntos de circulación."],["03","Terreno","Pendientes, apoyos, encuentros y condición del perímetro."]] },
  "/estructuras-metalicas": { eyebrow:"DEFINICIÓN TÉCNICA", title:"Función primero. Geometría después.", intro:"Antes de fabricar conviene separar lo que la estructura debe resolver de lo que todavía necesita definición técnica.", items:[["01","Función","Qué debe soportar, conectar, proteger o habilitar."],["02","Geometría","Plano, croquis, medidas y restricciones espaciales."],["03","Montaje","Acceso al lugar, secuencia y condiciones de instalación si aplica."]] },
  "/fabricacion-metalica": { eyebrow:"MATERIALES Y PROCESO", title:"El material se elige por el trabajo, no por costumbre.", intro:"RINON trabaja con acero estructural, acero inoxidable y aluminio estructural dentro de la factibilidad de cada requerimiento.", items:[["01","Acero estructural","Base habitual para productos, bastidores y estructuras."],["02","Acero inoxidable","Para requerimientos donde el material forme parte de la especificación."],["03","Aluminio estructural","Evaluado según geometría, unión y uso del conjunto."]] },
  "/equipamiento-metalico": { eyebrow:"DISEÑAR PARA EL USO", title:"El espacio y la operación mandan sobre el mueble.", intro:"Antes de decidir dimensiones conviene entender qué se almacenará, cómo se accederá y cuántas unidades se necesitan.", items:[["01","Uso","Qué debe guardar, ordenar, separar o soportar."],["02","Espacio","Huella disponible, accesos y restricciones del lugar."],["03","Cantidad","Una unidad, repetición o lote de fabricación."]] },
  "/camarote-con-escritorio": { eyebrow:"APROVECHAR EL ESPACIO", title:"La cama ocupa altura. El escritorio debe funcionar de verdad.", intro:"Antes de elegir una configuración conviene revisar el volumen disponible, la circulación y cómo se usará la zona de trabajo.", items:[["01","Volumen disponible","Ancho, largo y altura útil del dormitorio."],["02","Zona de trabajo","Uso del escritorio, silla, monitor y espacio de apoyo."],["03","Circulación","Escalera, accesos, puertas, ventanas y paso libre."]] },
  "/rejas-metalicas": { eyebrow:"DEFINIR LA PROTECCIÓN", title:"La geometría nace del vano, los apoyos y el nivel de cierre buscado.", intro:"Una reja útil no se define solo por alto y ancho: conviene entender dónde apoya, cómo se integra al entorno y qué acceso debe mantener.", items:[["01","Vano / tramo","Medidas aproximadas y relación con muros o apoyos."],["02","Acceso","Puertas, portones o zonas que deben permanecer operativas."],["03","Anclaje","Condición del lugar y puntos donde la solución puede fijarse."]] },
  "/portones-metalicos": { eyebrow:"RESOLVER EL ACCESO", title:"El movimiento del portón importa tanto como el tamaño del vano.", intro:"Ancho, alto y tipo de apertura se revisan junto con recorrido, apoyos y frecuencia de uso para evitar una solución que funcione en plano pero no en terreno.", items:[["01","Vano","Ancho, alto y condición de los apoyos existentes."],["02","Recorrido","Espacio lateral o radio de giro según apertura evaluada."],["03","Uso","Acceso peatonal, vehicular y frecuencia de operación."]] },
  "/pintura-electrostatica": { eyebrow:"ANTES DE RECIBIR LAS PIEZAS", title:"Geometría, estado y cantidad condicionan el proceso.", intro:"La terminación no se cotiza solo por color. Primero se revisa qué pieza llega, en qué condición y si sus dimensiones son compatibles con la operación habilitada.", items:[["01","Geometría","Dimensiones, forma y puntos de manipulación de cada pieza."],["02","Estado","Superficie actual y preparación necesaria antes de aplicar terminación."],["03","Lote","Cantidad, repetición y resultado esperado para la serie."]] },
  "/fabricaciones-especiales": { eyebrow:"PUNTO DE PARTIDA", title:"Una referencia incompleta puede ser suficiente para conversar.", intro:"Plano, croquis, fotografía, muestra física o medidas pueden servir para entender la función antes de confirmar factibilidad.", items:[["01","Plano / croquis","Geometría y relaciones principales."],["02","Foto / muestra","Referencia existente y contexto de uso."],["03","Medidas + función","Qué debe hacer la pieza y dónde debe trabajar."]] },
};

export function SolutionFeatureBand({ slug }: { slug: string }) {
  const band=bands[slug];
  if(!band) return null;
  return <section className="v2-feature-band"><div className="container"><div className="v2-feature-band-head"><div><span className="v2-eyebrow">{band.eyebrow}</span><h2>{band.title}</h2></div><p>{band.intro}</p></div><div className="v2-feature-band-grid">{band.items.map(([n,title,body])=><article key={n}><span>{n}</span><div><strong>{title}</strong><p>{body}</p></div></article>)}</div></div></section>;
}
