export interface BlogPost {
  slug: string;
  titulo: string;
  subtitulo: string;
  descripcionSeo: string;
  keywords: string[];
  fecha: string;
  categoria: string;
  tiempoLectura: string;
  imagen?: string;
}

export const blogPosts: BlogPost[] = [
  {
    slug: "camarote-con-escritorio-guia-completa",
    titulo: "Camarote con Escritorio: Guía Completa para Elegir el Mejor [2025]",
    subtitulo: "Todo lo que necesitas saber antes de comprar un camarote con escritorio en Chile",
    descripcionSeo: "Guía completa sobre camarotes con escritorio en Chile. Tipos, medidas, precios y cómo elegir el mejor modelo para dormitorio pequeño, universitario o gamer. Pago contra entrega en Santiago.",
    keywords: ["camarote con escritorio", "camarote con escritorio Chile", "cama alta con escritorio", "camarote escritorio precio"],
    fecha: "2025-01-15",
    categoria: "Guías",
    tiempoLectura: "8 min",
  },
  {
    slug: "camarote-nido-que-es",
    titulo: "¿Qué es un Camarote Nido? La Solución 3 en 1 para Piezas Pequeñas",
    subtitulo: "Descubre cómo un camarote nido puede triplicar las camas de tu dormitorio",
    descripcionSeo: "Qué es un camarote nido, cómo funciona y para quién es ideal. La solución perfecta para tener 3 camas en el espacio de 1. Disponible en Santiago con pago contra entrega.",
    keywords: ["camarote nido", "cama nido", "camarote con nido", "camarote 3 camas", "cama nido Chile"],
    fecha: "2025-01-20",
    categoria: "Productos",
    tiempoLectura: "6 min",
  },
  {
    slug: "cama-alta-vs-camarote",
    titulo: "Cama Alta vs Camarote: ¿Cuál te Conviene? Comparación Honesta",
    subtitulo: "Análisis detallado para que tomes la mejor decisión según tu espacio y necesidades",
    descripcionSeo: "Comparación completa entre cama alta y camarote. Ventajas, desventajas, precios y cuál elegir según el espacio disponible. Camarotes metálicos en Santiago, pago contra entrega.",
    keywords: ["cama alta vs camarote", "cama alta o camarote", "diferencia cama alta camarote", "cama loft vs camarote"],
    fecha: "2025-01-25",
    categoria: "Comparativas",
    tiempoLectura: "7 min",
  },
  {
    slug: "mejores-camarotes-chile",
    titulo: "Los Mejores Camarotes Metálicos en Chile [2025]: Guía de Compra",
    subtitulo: "Qué buscar al comprar un camarote metálico y dónde encontrar las mejores opciones en Santiago",
    descripcionSeo: "Guía actualizada de los mejores camarotes metálicos en Chile. Tipos, modelos, precios y consejos para elegir bien. Entrega en Santiago con pago contra entrega.",
    keywords: ["mejores camarotes Chile", "camarotes metálicos Chile", "camarote precio Chile", "donde comprar camarote Santiago"],
    fecha: "2025-02-01",
    categoria: "Guías",
    tiempoLectura: "9 min",
  },
  {
    slug: "camarote-dos-plazas",
    titulo: "Camarote de 2 Plazas en Chile: Todo lo que Debes Saber Antes de Comprar",
    subtitulo: "Modelos, medidas y consejos para elegir el camarote de dos plazas ideal",
    descripcionSeo: "Guía completa sobre camarotes de 2 plazas en Chile. Modelos con cama doble abajo, medidas y opciones disponibles en Santiago con pago contra entrega.",
    keywords: ["camarote 2 plazas", "camarote doble", "litera doble", "camarote matrimonial Chile"],
    fecha: "2025-02-05",
    categoria: "Productos",
    tiempoLectura: "7 min",
  },
  {
    slug: "camarote-plaza-y-media",
    titulo: "Camarote Plaza y Media en Chile: Más Comodidad en el Mismo Espacio",
    subtitulo: "Por qué el camarote de plaza y media es la mejor opción para adolescentes y adultos",
    descripcionSeo: "Todo sobre los camarotes de plaza y media en Chile. Combinaciones disponibles, ventajas frente al camarote estándar y cómo pedirlo con despacho en Santiago.",
    keywords: ["camarote plaza y media", "camarote 1.5 plazas", "camarote plaza y media con plaza", "camarote adolescente"],
    fecha: "2025-02-10",
    categoria: "Productos",
    tiempoLectura: "6 min",
  },
  {
    slug: "litera-metalica-chile",
    titulo: "Litera Metálica en Chile: Guía Completa [2025]",
    subtitulo: "Todo sobre literas metálicas: tipos, modelos, precios y cómo elegir la mejor para tu hogar",
    descripcionSeo: "Guía completa sobre literas metálicas en Chile. Diferencias entre litera y camarote, modelos disponibles y dónde comprar con entrega en Santiago.",
    keywords: ["litera metálica Chile", "litera Chile", "litera metalica Santiago", "camarote metalico Chile"],
    fecha: "2025-02-15",
    categoria: "Guías",
    tiempoLectura: "8 min",
  },
  {
    slug: "camarote-gamer-setup",
    titulo: "Setup Gamer con Cama Alta: Cómo Armar el Espacio Perfecto",
    subtitulo: "Guía para gamers que quieren aprovechar el espacio de su pieza al máximo",
    descripcionSeo: "Cómo armar un setup gamer perfecto usando una cama alta con escritorio. Ideas, consejos y productos disponibles en Santiago con pago contra entrega.",
    keywords: ["camarote gamer", "cama alta gamer", "setup gamer pieza pequeña", "cama loft gamer Chile"],
    fecha: "2025-02-20",
    categoria: "Inspiración",
    tiempoLectura: "7 min",
  },
  {
    slug: "donde-comprar-camarote-santiago",
    titulo: "¿Dónde Comprar un Camarote en Santiago? Guía Completa 2025",
    subtitulo: "Todo lo que necesitas saber para comprar un camarote metálico en Santiago sin errores",
    descripcionSeo: "Guía actualizada para comprar camarotes en Santiago. Qué buscar, cómo comparar precios, qué preguntar antes de comprar y dónde encontrar las mejores opciones con pago contra entrega.",
    keywords: ["donde comprar camarote Santiago", "comprar camarote Santiago", "camarote Santiago", "camarote metalico Santiago precio", "camarote entrega Santiago"],
    fecha: "2025-03-01",
    categoria: "Guías",
    tiempoLectura: "8 min",
  },
  {
    slug: "colchon-para-camarote",
    titulo: "¿Qué Colchón Usar en un Camarote? Guía de Medidas y Tipos [2025]",
    subtitulo: "Las claves para elegir el colchón correcto y no equivocarse con las medidas",
    descripcionSeo: "Guía completa para elegir el colchón de un camarote metálico en Chile. Medidas estándar, grosor recomendado, tipos de espuma y qué hacer cuando el colchón no entra. Santiago.",
    keywords: ["colchon para camarote", "colchón camarote medidas", "colchon plaza camarote", "grosor colchon camarote", "colchon nido camarote"],
    fecha: "2025-03-05",
    categoria: "Guías",
    tiempoLectura: "7 min",
  },
  {
    slug: "camarote-para-ninos",
    titulo: "Camarote para Niños: Guía para Padres [2025]",
    subtitulo: "Cómo elegir el camarote ideal para tus hijos: seguridad, medidas y modelos recomendados",
    descripcionSeo: "Todo lo que los padres necesitan saber para comprar un camarote para niños en Chile. Edad mínima, seguridad, modelos recomendados y cómo hacerlo con pago contra entrega en Santiago.",
    keywords: ["camarote para ninos", "camarote niños Chile", "camarote para piezas pequenas", "camarote infantil Santiago", "litera para ninos Chile"],
    fecha: "2025-03-10",
    categoria: "Guías",
    tiempoLectura: "9 min",
  },
  {
    slug: "camarote-matrimonial-chile",
    titulo: "Camarote Matrimonial en Chile: ¿Existe? Todo lo que Debes Saber",
    subtitulo: "Qué modelos de camarote tienen cama doble y cuándo conviene un camarote matrimonial",
    descripcionSeo: "¿Qué es un camarote matrimonial en Chile? Modelos con cama de 2 plazas, literas dobles y opciones para adultos. Pago contra entrega en Santiago. Consulta por WhatsApp.",
    keywords: ["camarote matrimonial", "camarote matrimonial Chile", "litera matrimonial", "camarote doble camas", "camarote 2 plazas Santiago"],
    fecha: "2025-03-15",
    categoria: "Guías",
    tiempoLectura: "6 min",
  },
  {
    slug: "armar-camarote-metalico",
    titulo: "Cómo Armar un Camarote Metálico: Guía Paso a Paso",
    subtitulo: "Todo lo que necesitas saber sobre el armado e instalación de camarotes metálicos",
    descripcionSeo: "Guía completa para armar un camarote metálico. Pasos, herramientas necesarias, tips para hacerlo solo o en pareja, y cómo evitar errores comunes. Camarotes con instalación en Santiago.",
    keywords: ["como armar camarote metalico", "armar camarote metalico", "instalar camarote", "armar litera metalica", "camarote metalico instrucciones"],
    fecha: "2025-03-20",
    categoria: "Guías",
    tiempoLectura: "8 min",
  },
  {
    slug: "camarote-adultos",
    titulo: "Camarote para Adultos en Chile: Modelos y Recomendaciones [2025]",
    subtitulo: "Los mejores modelos de camarote para adultos: comodidad, resistencia y opciones disponibles",
    descripcionSeo: "Guía de camarotes para adultos en Chile. Qué modelos ofrecen mayor comodidad, mayor resistencia y mayor espacio para adultos. Pago contra entrega en Santiago.",
    keywords: ["camarote para adultos", "camarote adultos Chile", "litera adultos Chile", "camarote adultos Santiago", "camarote 2 adultos"],
    fecha: "2025-03-25",
    categoria: "Guías",
    tiempoLectura: "7 min",
  },
  {
    slug: "medidas-camarote-estandar",
    titulo: "Medidas de un Camarote Estándar en Chile: Ancho, Largo y Alto [2025]",
    subtitulo: "Guía completa de medidas para saber qué camarote cabe en tu espacio",
    descripcionSeo: "Medidas estándar de camarotes metálicos en Chile. Ancho, largo y alto de cada modelo. Cómo medir tu espacio antes de comprar. Despacho en Santiago con pago contra entrega.",
    keywords: ["medidas camarote", "medidas camarote estandar", "tamaño camarote Chile", "ancho camarote", "largo camarote", "medidas litera Chile"],
    fecha: "2025-04-01",
    categoria: "Guías",
    tiempoLectura: "6 min",
  },
  {
    slug: "camarote-segunda-mano-vs-nuevo",
    titulo: "Camarote de Segunda Mano vs Nuevo: ¿Cuál Conviene en Chile?",
    subtitulo: "Análisis honesto entre comprar un camarote usado o uno nuevo en Chile",
    descripcionSeo: "¿Vale la pena comprar un camarote de segunda mano en Chile? Comparación de costos, riesgos y ventajas frente a un camarote metálico nuevo. Camarotes nuevos con pago contra entrega en Santiago.",
    keywords: ["camarote segunda mano", "camarote usado Chile", "comprar camarote usado Santiago", "camarote segunda mano Santiago", "litera segunda mano Chile"],
    fecha: "2025-04-05",
    categoria: "Comparativas",
    tiempoLectura: "7 min",
  },
  {
    slug: "como-elegir-camarote",
    titulo: "Cómo Elegir un Camarote: Guía Completa para No Equivocarse [2025]",
    subtitulo: "Las preguntas clave que debes hacerte antes de comprar un camarote en Chile",
    descripcionSeo: "Guía paso a paso para elegir el camarote correcto en Chile. Qué preguntas hacerse, qué modelos existen y cómo no cometer errores al comprar. Pago contra entrega en Santiago.",
    keywords: ["como elegir camarote", "guia compra camarote Chile", "elegir camarote metalico", "que camarote comprar Chile", "camarote cual elegir"],
    fecha: "2025-04-10",
    categoria: "Guías",
    tiempoLectura: "9 min",
  },
  {
    slug: "cuanto-cuesta-camarote-chile",
    titulo: "¿Cuánto Cuesta un Camarote en Chile? Guía de Precios 2025",
    subtitulo: "Factores que influyen en el precio de un camarote metálico y qué esperar al cotizar",
    descripcionSeo: "Guía de precios de camarotes metálicos en Chile 2025. Qué factores determinan el precio, qué incluye el costo y cómo cotizar con pago contra entrega en Santiago.",
    keywords: ["cuanto cuesta camarote Chile", "precio camarote Chile", "camarote metalico precio", "costo camarote Santiago", "camarote precio 2025"],
    fecha: "2025-04-15",
    categoria: "Guías",
    tiempoLectura: "6 min",
  },
  {
    slug: "camarote-para-departamento",
    titulo: "Camarote para Departamento Pequeño: La Solución para Piezas sin Espacio",
    subtitulo: "Cómo elegir el camarote correcto cuando tu departamento tiene espacio limitado",
    descripcionSeo: "Camarotes para departamentos pequeños en Santiago. Modelos compactos, opciones con escritorio y cómo aprovechar el espacio vertical. Pago contra entrega.",
    keywords: ["camarote departamento pequeño", "camarote pieza pequeña", "camarote espacio reducido Santiago", "camarote departamento Santiago", "litera departamento Chile"],
    fecha: "2025-04-20",
    categoria: "Inspiración",
    tiempoLectura: "7 min",
  },
  {
    slug: "camarote-vs-cama-individual",
    titulo: "Camarote vs Dos Camas Individuales: ¿Qué Conviene Más? [2025]",
    subtitulo: "Análisis honesto entre comprar un camarote o dos camas separadas para una misma pieza",
    descripcionSeo: "Comparación completa entre camarote y dos camas individuales en Chile. Espacio, precio, comodidad y cuándo conviene cada opción. Santiago, pago contra entrega.",
    keywords: ["camarote vs dos camas", "camarote o dos camas individuales", "ventajas camarote", "camarote vs camas separadas Chile"],
    fecha: "2025-04-25",
    categoria: "Comparativas",
    tiempoLectura: "7 min",
  },
  {
    slug: "camarote-para-hostal",
    titulo: "Camarote para Hostal o Pensión: Qué Buscar y Qué Evitar",
    subtitulo: "Guía de camarotes metálicos para uso intensivo en hostales, pensiones y residencias",
    descripcionSeo: "Cómo elegir camarotes para hostal, pensión o residencia en Chile. Resistencia, capacidad de peso, fácil mantenimiento y modelos recomendados para uso intensivo. Despacho en Santiago.",
    keywords: ["camarote hostal Chile", "camarote pension", "camarote uso intensivo", "litera hostal Chile", "camarote residencia Santiago"],
    fecha: "2025-05-01",
    categoria: "Guías",
    tiempoLectura: "7 min",
  },
  {
    slug: "mantenimiento-camarote-metalico",
    titulo: "Cómo Limpiar y Mantener un Camarote Metálico [Guía 2025]",
    subtitulo: "Todo lo que necesitas saber para que tu camarote metálico dure muchos años",
    descripcionSeo: "Guía de mantenimiento y limpieza de camarotes metálicos en Chile. Cómo limpiar el acero, prevenir el óxido y mantener la pintura en perfectas condiciones. Tips prácticos.",
    keywords: ["limpiar camarote metalico", "mantenimiento camarote metalico", "mantenimiento litera acero", "camarote metalico oxido", "cuidar camarote metalico"],
    fecha: "2025-05-05",
    categoria: "Guías",
    tiempoLectura: "6 min",
  },
  {
    slug: "camarote-regalo",
    titulo: "Camarote como Regalo: Cómo Comprarlo y Coordinarlo sin Sorpresas",
    subtitulo: "Guía para regalar un camarote metálico en Santiago de forma fácil y sin errores",
    descripcionSeo: "Cómo comprar un camarote metálico como regalo en Chile. Coordinación de medidas, despacho y pago. La guía para que el regalo llegue perfecto. Santiago, pago contra entrega.",
    keywords: ["camarote regalo", "regalar camarote Chile", "comprar camarote regalo Santiago", "camarote regalo ninos"],
    fecha: "2025-05-10",
    categoria: "Guías",
    tiempoLectura: "5 min",
  },
  {
    slug: "camarote-nino-6-anos",
    titulo: "Camarote para Niño de 6 Años: Cuándo es Seguro y Qué Modelo Elegir",
    subtitulo: "Todo lo que necesitas saber antes de comprar la primera cama alta o camarote para tu hijo",
    descripcionSeo: "¿A qué edad puede un niño dormir en camarote? Guía de seguridad para camarotes de niños de 6 años en Chile. Qué modelo elegir, altura recomendada y medidas de seguridad.",
    keywords: ["camarote niño 6 años", "primera cama alta niño", "camarote niños Chile", "literas niños edad minima", "camarote seguro niños"],
    fecha: "2025-05-15",
    categoria: "Guías",
    tiempoLectura: "6 min",
  },
  {
    slug: "decorar-habitacion-camarote",
    titulo: "Cómo Decorar una Habitación con Camarote [Ideas 2025]",
    subtitulo: "Ideas prácticas para decorar y organizar una pieza pequeña con camarote metálico",
    descripcionSeo: "Ideas para decorar una habitación con camarote en Chile. Cómo aprovechar el espacio, qué poner debajo de la cama alta, colores y organización. Habitaciones pequeñas con literas.",
    keywords: ["decorar habitacion camarote", "decorar pieza con camarote", "habitacion con literas", "pieza con camarote ideas", "organizar cuarto camarote"],
    fecha: "2025-05-20",
    categoria: "Decoración",
    tiempoLectura: "7 min",
  },
  {
    slug: "camarote-segunda-mano-donde-comprar",
    titulo: "Camarote de Segunda Mano en Santiago: Lo que Nadie te Dice",
    subtitulo: "Comparativa honesta entre camarotes nuevos y de segunda mano en Chile",
    descripcionSeo: "Comprar camarote de segunda mano en Santiago: riesgos reales, cómo evaluar el estado, precio justo y cuándo vale más comprar nuevo. Guía honesta y sin filtros.",
    keywords: ["camarote segunda mano Santiago", "camarote usado Santiago", "comprar camarote segunda mano Chile", "literas segunda mano Chile"],
    fecha: "2025-05-25",
    categoria: "Comparativas",
    tiempoLectura: "6 min",
  },
  {
    slug: "pieza-compartida-hermanos",
    titulo: "Pieza para 2 Hermanos: Cómo Organizar una Habitación para Compartir",
    subtitulo: "Guía práctica para organizar una habitación de dos hermanos con camarote",
    descripcionSeo: "Cómo organizar una pieza para 2 hermanos con camarote en Chile. Ideas de distribución, camarotes recomendados, almacenamiento y cómo dar privacidad a cada uno.",
    keywords: ["pieza para 2 hermanos", "habitacion compartida hermanos", "organizar cuarto dos ninos", "camarote hermanos Chile", "pieza dos camas Santiago"],
    fecha: "2025-06-01",
    categoria: "Guías",
    tiempoLectura: "7 min",
  },
  {
    slug: "camarote-universitario",
    titulo: "Camarote para Universitarios: La Solución para Dormitorios Pequeños en Santiago",
    subtitulo: "Guía de camarotes para estudiantes universitarios que comparten pieza en Santiago",
    descripcionSeo: "Camarotes para universitarios en Santiago. Cómo elegir el mejor camarote para una pieza pequeña, compartida o para estudiar. Pago contra entrega. Despacho en Santiago.",
    keywords: ["camarote universitario Santiago", "camarote estudiante universitario", "litera universitario Chile", "dormitorio universitario Santiago", "camarote para estudiante"],
    fecha: "2025-06-05",
    categoria: "Guías",
    tiempoLectura: "6 min",
  },
  {
    slug: "camarote-vs-cucheta",
    titulo: "Camarote vs Cucheta: ¿Cuál es la Diferencia? [Guía Chile 2025]",
    subtitulo: "Aclaramos la confusión entre camarote, cucheta y litera en Chile",
    descripcionSeo: "¿Cuál es la diferencia entre camarote, cucheta y litera en Chile? Guía completa con la terminología correcta y qué buscar al comparar modelos. Santiago, pago contra entrega.",
    keywords: ["camarote vs cucheta", "diferencia camarote cucheta", "cucheta Chile", "litera vs camarote", "cucheta metalica Chile"],
    fecha: "2025-06-10",
    categoria: "Comparativas",
    tiempoLectura: "5 min",
  },
  {
    slug: "camarote-para-adulto-mayor",
    titulo: "Camarote para Adulto Mayor: ¿Es Seguro y Qué Considerar?",
    subtitulo: "Guía honesta sobre el uso de camarotes por personas mayores en Chile",
    descripcionSeo: "¿Puede un adulto mayor usar un camarote? Guía de seguridad, modelos recomendados y qué evitar. Alternativas para personas mayores en Chile. Pago contra entrega Santiago.",
    keywords: ["camarote adulto mayor", "litera persona mayor Chile", "camarote seguro adulto mayor", "cama alta adultos mayores", "camarote persona mayor Santiago"],
    fecha: "2025-06-12",
    categoria: "Guías",
    tiempoLectura: "6 min",
  },
  {
    slug: "camarote-armado-paso-a-paso",
    titulo: "Cómo Se Arma un Camarote Metálico [Guía Paso a Paso]",
    subtitulo: "Todo sobre el armado de camarotes metálicos: tiempos, herramientas y qué esperar",
    descripcionSeo: "Cómo se arma un camarote metálico en Chile paso a paso. Herramientas necesarias, tiempo de instalación y qué esperar del proceso. Con nuestro servicio, el equipo lo arma por ti.",
    keywords: ["armar camarote metalico", "instrucciones camarote metalico", "como armar litera metalica", "armado camarote Chile", "instalar camarote Santiago"],
    fecha: "2025-06-15",
    categoria: "Guías",
    tiempoLectura: "5 min",
  },
  {
    slug: "camarote-con-cajones",
    titulo: "Camarote con Cajones: ¿Existe y Vale la Pena?",
    subtitulo: "Todo sobre almacenamiento integrado en camarotes metálicos en Chile",
    descripcionSeo: "¿Existen camarotes metálicos con cajones en Chile? Alternativas de almacenamiento para camarotes, qué opciones hay y cómo maximizar el espacio bajo la cama. Santiago, pago contra entrega.",
    keywords: ["camarote con cajones", "camarote con almacenamiento Chile", "litera cajones Santiago", "camarote metalico cajones", "almacenamiento bajo camarote"],
    fecha: "2025-06-18",
    categoria: "Guías",
    tiempoLectura: "5 min",
  },
  {
    slug: "camarote-metalico-vs-madera",
    titulo: "Camarote Metálico vs Madera: ¿Cuál Conviene en Chile? [2025]",
    subtitulo: "Comparativa honesta entre camarotes de acero y de madera para ayudarte a decidir",
    descripcionSeo: "¿Camarote metálico o de madera? Comparativa de durabilidad, precio, peso soportado y mantenimiento. Qué conviene más para una familia en Chile. Guía 2025.",
    keywords: ["camarote metalico vs madera", "camarote metal o madera Chile", "litera metalica vs madera", "mejor material camarote Chile"],
    fecha: "2025-06-20",
    categoria: "Comparativas",
    tiempoLectura: "6 min",
  },
  {
    slug: "pago-contra-entrega-camarote",
    titulo: "Pago Contra Entrega en Camarotes: Por Qué Es la Forma Más Segura de Comprar",
    subtitulo: "Cómo funciona el pago contra entrega y por qué protege al comprador",
    descripcionSeo: "¿Qué significa pago contra entrega en camarotes? Cómo funciona, qué protege y por qué es la forma más segura de comprar un camarote en Chile. Santiago, instalación incluida.",
    keywords: ["pago contra entrega camarote Chile", "comprar camarote pago contra entrega", "camarote sin pago adelantado Santiago", "camarote pago cuando llega"],
    fecha: "2025-06-22",
    categoria: "Guías",
    tiempoLectura: "4 min",
  },
  {
    slug: "camarote-para-pieza-pequena",
    titulo: "Camarote para Pieza Pequeña: Las Mejores Opciones en Chile",
    subtitulo: "Cómo elegir el camarote correcto cuando el espacio es muy limitado",
    descripcionSeo: "Las mejores opciones de camarotes para piezas pequeñas en Chile. Modelos que ahorran espacio, medidas mínimas recomendadas y cómo calcular si el camarote entra. Santiago.",
    keywords: ["camarote pieza pequeña", "camarote espacio reducido Chile", "camarote departamento pequeño Santiago", "litera pieza chica Chile", "camarote ahorra espacio"],
    fecha: "2025-06-24",
    categoria: "Guías",
    tiempoLectura: "6 min",
  },
  {
    slug: "como-equipar-campamento-minero",
    titulo: "Cómo Equipar un Campamento Minero: Guía Completa de Alojamiento",
    subtitulo: "Todo lo que necesitas saber para amueblar un campamento de trabajadores mineros en Chile",
    descripcionSeo: "Guía para equipar campamentos mineros en Chile. Cuántas camas se necesitan, qué tipo de camarote aguanta el uso intensivo, normativas SERNAGEOMIN y cómo cotizar. Antofagasta, Calama, Copiapó.",
    keywords: ["equipar campamento minero Chile", "camarotes campamento minero", "alojamiento trabajadores mineros", "camas faena minera", "campamento minero camarotes"],
    fecha: "2026-01-10",
    categoria: "Empresas",
    tiempoLectura: "8 min",
  },
  {
    slug: "diferencias-camarotes-industriales-residenciales",
    titulo: "Camarotes Industriales vs Residenciales: ¿Cuál Necesitas?",
    subtitulo: "Las diferencias reales entre un camarote para uso doméstico y uno para faenas o campamentos",
    descripcionSeo: "Diferencias entre camarotes industriales y residenciales en Chile. Calibre del acero, soldaduras, peso, medidas, normativas y precio. Guía para elegir correctamente.",
    keywords: ["camarote industrial vs residencial", "camarotes faena diferencias", "camarote campamento vs hogar", "camarotes uso intensivo Chile"],
    fecha: "2026-01-20",
    categoria: "Empresas",
    tiempoLectura: "6 min",
  },
  {
    slug: "camarotes-para-temporeros",
    titulo: "Camarotes para Temporeros: Guía de Alojamiento Agrícola en Chile",
    subtitulo: "Cómo organizar el alojamiento para trabajadores de temporada en fundos, viñas y packing",
    descripcionSeo: "Guía para equipar alojamiento de temporeros en Chile. Qué tipo de camarote usar, cuántos necesitas según la cuadrilla, normativa del MINSAL y cómo cotizar. Curicó, Talca, Valle del Maule.",
    keywords: ["camarotes temporeros Chile", "alojamiento temporeros packing", "camas trabajadores temporada", "camarotes agrícolas Chile", "alojamiento cuadrilla agrícola"],
    fecha: "2026-02-05",
    categoria: "Empresas",
    tiempoLectura: "7 min",
  },
  {
    slug: "proveedor-camarotes-empresas",
    titulo: "Cómo Elegir un Proveedor de Camarotes para Empresas en Chile",
    subtitulo: "Los criterios que debe cumplir tu proveedor de camas y camarotes para proyectos industriales",
    descripcionSeo: "Guía para elegir proveedor de camarotes para empresas en Chile. Fabricante vs distribuidor, garantías, plazos, factura, despacho nacional y precio mayorista.",
    keywords: ["proveedor camarotes empresas Chile", "fabricante camarotes Chile", "camarotes empresa cotización", "comprar camarotes al por mayor Chile"],
    fecha: "2026-02-18",
    categoria: "Empresas",
    tiempoLectura: "5 min",
  },
  {
    slug: "mejor-camarote-con-escritorio-chile",
    titulo: "El Mejor Camarote con Escritorio en Chile — Guía de Compra 2026",
    subtitulo: "Cómo elegir el modelo correcto sin equivocarte en medidas, material ni precio",
    descripcionSeo: "Guía de compra del mejor camarote con escritorio en Chile 2026. Qué mirar en el acero, qué medidas importan, cómo evitar los errores más comunes y dónde comprar directo al fabricante.",
    keywords: ["mejor camarote con escritorio chile", "camarote con escritorio guía compra", "camarote escritorio recomendado chile", "cuál camarote con escritorio comprar"],
    fecha: "2026-03-05",
    categoria: "Guías",
    tiempoLectura: "7 min",
  },
  {
    slug: "camarote-escritorio-vs-escritorio-aparte",
    titulo: "Camarote con Escritorio vs Escritorio Aparte — ¿Qué Conviene Más?",
    subtitulo: "Un análisis honesto de cuándo el escritorio integrado gana y cuándo no",
    descripcionSeo: "Comparativa honesta: camarote con escritorio integrado vs cama + escritorio por separado. Cuándo conviene cada opción según el espacio, el presupuesto y el uso.",
    keywords: ["camarote escritorio vs escritorio aparte", "cama alta escritorio separado", "camarote integrado o escritorio separado", "cuándo comprar camarote escritorio"],
    fecha: "2026-03-18",
    categoria: "Guías",
    tiempoLectura: "6 min",
  },
  {
    slug: "como-crear-zona-de-estudio-dormitorio",
    titulo: "Cómo Crear una Zona de Estudio en un Dormitorio Pequeño",
    subtitulo: "Ideas concretas que funcionan, desde el camarote con escritorio hasta distribuciones que aprovechan cada m²",
    descripcionSeo: "Cómo organizar una zona de estudio en un dormitorio pequeño. Ideas prácticas, distribuciones posibles y por qué el camarote con escritorio es la solución más eficiente en espacio.",
    keywords: ["zona de estudio dormitorio pequeño", "cómo organizar dormitorio estudio", "escritorio en pieza pequeña", "espacio estudio dormitorio ideas"],
    fecha: "2026-04-02",
    categoria: "Consejos",
    tiempoLectura: "6 min",
  },
  {
    slug: "pintura-electrostatica-muebles-metalicos",
    titulo: "Pintura Electrostática en Muebles Metálicos — Qué Es y Por Qué Dura Más",
    subtitulo: "Explicamos el proceso desde adentro: por qué la pintura en polvo supera a la convencional y cómo se aplica en un taller real",
    descripcionSeo: "Qué es la pintura electrostática en muebles metálicos y por qué dura más que la pintura convencional. Proceso de powder coating explicado por fabricantes.",
    keywords: ["pintura electrostática muebles metálicos", "powder coating Chile", "pintura en polvo ventajas", "pintura electrostática vs convencional", "proceso pintura electrostática"],
    fecha: "2026-04-15",
    categoria: "Fabricación",
    tiempoLectura: "5 min",
  },
  {
    slug: "camarotes-metalicos-vs-madera",
    titulo: "Camarote Metálico vs Madera — Comparativa Real desde el Taller",
    subtitulo: "No vendemos madera, así que podemos ser honestos: cuándo el metal gana y cuándo no",
    descripcionSeo: "Comparativa honesta entre camarotes metálicos y de madera. Durabilidad, peso, precio, sonido, mantenimiento. Escrito por un fabricante de camarotes metálicos.",
    keywords: ["camarote metálico vs madera", "camarote acero o madera", "mejor material camarote", "camarote hierro o madera"],
    fecha: "2026-05-01",
    categoria: "Guías",
    tiempoLectura: "6 min",
  },
];

export function getBlogPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}

export function getBlogPostsByCategory(categoria: string): BlogPost[] {
  return blogPosts.filter((p) => p.categoria === categoria);
}
